image: python:3.11-slim

stages:
  - test

# Cache pip downloads to speed up future jobs
cache:
  paths:
    - .cache/pip

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
  stage: test
  tags:
    - docker
  script:
    # Create and activate a virtual environment
    - python -m venv venv
    - source venv/bin/activate
    # Upgrade pip, install your package in editable mode, and install pytest
    - pip install --upgrade pip
    - pip install -e .
    - pip install pytest
    - pytest tests
